/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ControllerLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Paulo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new ControllerLogin(this);
    }

    public JButton getBtircadastro() {
        return btircadastro;
    }

    public void setBtircadastro(JButton btircadastro) {
        this.btircadastro = btircadastro;
    }

    public JButton getBtlogin() {
        return btlogin;
    }

    public void setBtlogin(JButton btlogin) {
        this.btlogin = btlogin;
    }

    public JLabel getLblCPF() {
        return lblCPF;
    }

    public void setLblCPF(JLabel lblCPF) {
        this.lblCPF = lblCPF;
    }

    public JLabel getLblrlogin() {
        return lblrlogin;
    }

    public void setLblrlogin(JLabel lblrlogin) {
        this.lblrlogin = lblrlogin;
    }

    public JLabel getLblsenha() {
        return lblsenha;
    }

    public void setLblsenha(JLabel lblsenha) {
        this.lblsenha = lblsenha;
    }

    public JTextField getTxtCPF() {
        return txtCPF;
    }

    public void setTxtCPF(JTextField txtCPF) {
        this.txtCPF = txtCPF;
    }

    public JTextField getTxtsenha() {
        return txtsenha;
    }

    public void setTxtsenha(JTextField txtsenha) {
        this.txtsenha = txtsenha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblrlogin = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        btlogin = new javax.swing.JButton();
        btircadastro = new javax.swing.JButton();
        txtCPF = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblrlogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblrlogin.setText("Realize o Login");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF:");

        lblsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsenha.setText("Senha:");

        btlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });

        btircadastro.setBackground(new java.awt.Color(242, 242, 242));
        btircadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btircadastro.setForeground(new java.awt.Color(54, 23, 212));
        btircadastro.setText("Realize o cadastro caso não o tenha");
        btircadastro.setBorder(null);
        btircadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btircadastroActionPerformed(evt);
            }
        });

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsenha)
                            .addComponent(lblCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txtCPF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btlogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblrlogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btircadastro)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblrlogin)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsenha)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btlogin)
                .addGap(29, 29, 29)
                .addComponent(btircadastro)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        controller.LoginInvestidor();
    }//GEN-LAST:event_btloginActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void btircadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btircadastroActionPerformed
       Cadastro cf = new Cadastro();
       cf.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btircadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    private ControllerLogin controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btircadastro;
    private javax.swing.JButton btlogin;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblrlogin;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables
}
