/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import control.ControllerSenha;
import control.ControllerLoginSaldo;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import control.ControllerSenha;
import model.Investidor;


/**
 *
 * @author Paulo
 */
public class Senha extends javax.swing.JFrame {


    
    public Senha(Investidor investidor ) {
        initComponents();
        
        
    }

    public JTextField getTxtsenha() {
        return Txtsenha;
    }

    public void setTxtsenha(JTextField Txtsenha) {
        this.Txtsenha = Txtsenha;
    }

    public JButton getBtsennha() {
        return btsennha;
    }

    public void setBtsennha(JButton btsennha) {
        this.btsennha = btsennha;
    }

    public JLabel getLblsenha() {
        return lblsenha;
    }

    public void setLblsenha(JLabel lblsenha) {
        this.lblsenha = lblsenha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        Txtsenha = new javax.swing.JTextField();
        btsennha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Confirmação");

        lblsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblsenha.setText("Senha:");

        btsennha.setText("Inserir");
        btsennha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsennhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblsenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btsennha)
                            .addComponent(Txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsenha)
                    .addComponent(Txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btsennha)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsennhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsennhaActionPerformed
        
    }//GEN-LAST:event_btsennhaActionPerformed

    /**
     * @param args the command line arguments
     */
    private ControllerLoginSaldo controller;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtsenha;
    private javax.swing.JButton btsennha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblsenha;
    // End of variables declaration//GEN-END:variables


}
