/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ControllerCadastro;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Paulo
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        controller = new ControllerCadastro(this);
    }

    public JButton getBtcadastra() {
        return Btcadastra;
    }

    public void setBtcadastra(JButton Btcadastra) {
        this.Btcadastra = Btcadastra;
    }

    public JLabel getLblCPF() {
        return LblCPF;
    }

    public void setLblCPF(JLabel LblCPF) {
        this.LblCPF = LblCPF;
    }

    public JLabel getLblcadastro() {
        return Lblcadastro;
    }

    public void setLblcadastro(JLabel Lblcadastro) {
        this.Lblcadastro = Lblcadastro;
    }

    public JLabel getLblnome() {
        return Lblnome;
    }

    public void setLblnome(JLabel Lblnome) {
        this.Lblnome = Lblnome;
    }

    public JLabel getLblsenha() {
        return Lblsenha;
    }

    public void setLblsenha(JLabel Lblsenha) {
        this.Lblsenha = Lblsenha;
    }

    public JTextField getTxtCPF() {
        return TxtCPF;
    }

    public void setTxtCPF(JTextField TxtCPF) {
        this.TxtCPF = TxtCPF;
    }

    public JTextField getTxtnome() {
        return Txtnome;
    }

    public void setTxtnome(JTextField Txtnome) {
        this.Txtnome = Txtnome;
    }

    public JTextField getTxtsenha() {
        return Txtsenha;
    }

    public void setTxtsenha(JTextField Txtsenha) {
        this.Txtsenha = Txtsenha;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lblcadastro = new javax.swing.JLabel();
        LblCPF = new javax.swing.JLabel();
        Lblsenha = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        Txtsenha = new javax.swing.JTextField();
        Btcadastra = new javax.swing.JButton();
        Lblnome = new javax.swing.JLabel();
        Txtnome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lblcadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lblcadastro.setText("Cadastro");

        LblCPF.setText("CPF:");

        Lblsenha.setText("Senha:");

        TxtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCPFActionPerformed(evt);
            }
        });

        Txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtsenhaActionPerformed(evt);
            }
        });

        Btcadastra.setText("Cadastrar");
        Btcadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtcadastraActionPerformed(evt);
            }
        });

        Lblnome.setText("Nome:");

        Txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCPF)
                                    .addComponent(Lblsenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(TxtCPF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lblnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(Lblcadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(Btcadastra)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Lblcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblnome)
                    .addComponent(Txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCPF)
                    .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblsenha)
                    .addComponent(Txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Btcadastra)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtcadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtcadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtcadastraActionPerformed

    private void TxtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtsenhaActionPerformed

    private void TxtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCPFActionPerformed

    private void TxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btcadastra;
    private javax.swing.JLabel LblCPF;
    private javax.swing.JLabel Lblcadastro;
    private javax.swing.JLabel Lblnome;
    private javax.swing.JLabel Lblsenha;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField Txtnome;
    private javax.swing.JTextField Txtsenha;
    // End of variables declaration//GEN-END:variables
}
